// Generated by CoffeeScript 1.10.0
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var demos, logo, methods;
    if (!OriDomi.isSupported) {
      document.getElementById('unsupported').style.display = 'block';
      return;
    }
    logo = new OriDomi('.logo', {
      shading: false,
      speed: 1000
    });
    logo.stairs(17);
    demos = [
      new OriDomi('.demo1', {
        vPanels: 5,
        ripple: true
      }), new OriDomi('.demo1_1', {
        vPanels: 5,
        ripple: true
      }), new OriDomi('.demo1_2', {
        vPanels: 5,
        ripple: true
      }), new OriDomi('.demo1_3', {
        vPanels: 5,
        ripple: true
      }), new OriDomi('.demo1_4', {
        vPanels: 5,
        ripple: true
      }), new OriDomi('.demo1_5', {
        vPanels: 5,
        ripple: true
      }), new OriDomi('.demo1_6', {
        vPanels: 5,
        ripple: true
      }), new OriDomi('.demo4', {
        vPanels: 4,
        ripple: true
      }), new OriDomi('.demo6', {
        hPanels: 4,
        ripple: true,
        shading: false
      })
    ];
    setTimeout(function() {
      demos[0].accordion(29, 'left');
      demos[1].accordion(-25, 'right');
      demos[2].accordion(-30, 'bottom');
      demos[3].accordion(-27, 'right');
      demos[4].accordion(-20, 'left');
      demos[5].stairs(18, 'right');
      demos[6].stairs(7,'top');
      demos[7].stairs(20, 'bottom');
      return demos[8].reveal(45, 'top');
    }, 1000);
    methods = ['accordion', 'stairs', 'curl', 'reveal', 'foldUp', 'ramp', 'twist', 'fracture'];
    return document.getElementById('demos').addEventListener('click', function(e) {
      var angle, el, method, n;
      if ((el = e.target).className !== 'button') {
        return;
      }
      n = el.getAttribute('data-n');
      method = methods[Math.abs(Math.floor(Math.random() * methods.length - Math.random()))];
      angle = Math.floor(Math.random() * 80 * (Math.random() > .5 ? -1 : 1));
      demos[n][method](method !== 'foldUp' ? angle : void 0);
      if (method === 'foldUp') {
        angle = '';
      }
      return el.parentNode.getElementsByClassName('label')[0].innerHTML = method + "(" + angle + ")";
    }, false);
  });

}).call(this);

//# sourceMappingURL=demo.js.map
